public class C3 {
        int x= 645;


                                    //NO return type in constructors
     C3(){                     // constructor modifier is same as class modifier
        super();                   // First line in the block must be super() or this() // Do not write both anywhere else.
     System.out.println("Prototype of Constructors");     // This is not default constructor.Programmers constructor
                                  // default constructor is generated by compiler when there is no constructor in program
    }

    public static void main(String [] args){

        C3 a = new C3();
      //  super()   // It should be used in constructor only to call super class constructor.
        // that()  //It should be used in constructor only to call current class constructor.

    }

}

class z extends C3{
    public void m1(){
        int x =850;
        System.out.println(super.x); // super is the keyword to refer top class(super class) instance members
        System.out.println(this.x); // this is the keyword to refer current class instance member.
    }

}
